import { PluginSettings } from 'src/types';
import { GoogleGenAI } from '@google/genai';

/**
 * Service for interacting with Gemini AI.
 * This class provides methods for summarizing video transcripts using Gemini AI.
 * It utilizes the GoogleGenAI library to interact with the Gemini API.
 */
export class GeminiService {
	private genAI: GoogleGenAI;
	private model: string | null = null;

	/**
	 * Creates an instance of GeminiService.
	 * @param settings - The plugin settings.
	 */
	constructor(private settings: PluginSettings) {
		// Initialize the Gemini AI client
		this.genAI = new GoogleGenAI({apiKey: settings.geminiApiKey});
	}

	/**
	 * Initializes the Gemini model.
	 * Call this method after creating an instance.
	 */
	public async initialize(): Promise<void> {
		// Store the model name
		this.model = this.settings.selectedModel;
	}

	/**
	 * Summarizes video transcript using Gemini AI
	 * @param prompt - Prompt for AI
	 * @returns Structured summary response
	 */
	async summarize(prompt: string): Promise<string> {
		if (!this.model) {
			await this.initialize();
		}
		
		// Ensure model is initialized
		if (!this.model) {
			throw new Error("Failed to initialize Gemini model");
		}
		
		// Build the prompt for Gemini AI
		try {
			// Generate content using Gemini
			const response = await this.genAI.models.generateContent({
				model: this.model,
				contents: prompt
			});
			
			// Access response text directly based on the latest @google/genai SDK
			// Handle the case where text might be undefined
			if (!response.text) {
				return "No text was generated by the model.";
			}
			return response.text;
		} catch (error) {
			throw new Error(`Gemini API error: ${error.message}`);
		}
	}

	/**
	 * Fetches all available Gemini models from the API
	 * @returns Array of Gemini model names
	 */
	async getGeminiModels(): Promise<string[]> {
		try {
			// Currently the API doesn't provide a direct way to list models
			// Return a predefined list of common Gemini models
			return [
				'gemini-pro', 
				'gemini-pro-vision', 
				'gemini-1.5-pro', 
				'gemini-1.5-flash',
				'gemini-2.0-flash-001',
				'gemini-2.0-pro-001',
				'gemini-2.5-flash-preview-04-17'
			];
		} catch (error) {
			throw new Error(`Failed to fetch Gemini models: ${error.message}`);
		}
	}
}
